name: kitap_okuma_app
description: İlkokul 1-4. sınıflar için kitap okuma uygulaması

publish_to: 'none' # Paket olarak yayınlamıyorsan

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.4.0
  firebase_storage: ^11.0.7
  cloud_firestore: ^4.5.0
  flutter_tts: ^3.5.2
  intl: ^0.18.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_logo.png
