// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD4Dkpow9NHSiY5PdZ-MBHKg8tvUPesj8',
    appId: '1:132808024282:web:1af1362a606e7457bd85e3',
    messagingSenderId: '132808024282',
    projectId: 'kitapokumaapp-cb587',
    authDomain: 'kitapokumaapp-cb587.firebaseapp.com',
    storageBucket: 'kitapokumaapp-cb587.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9tWttlRK0cjUUczp6sN9kPnICyQcBePU',
    appId: '1:132808024282:android:fcf7eee4cbe0b368bd85e3',
    messagingSenderId: '132808024282',
    projectId: 'kitapokumaapp-cb587',
    storageBucket: 'kitapokumaapp-cb587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OkkRrLzptj2jTZMg0twDihO-lwcKOgQ',
    appId: '1:132808024282:ios:23d079751ac83260bd85e3',
    messagingSenderId: '132808024282',
    projectId: 'kitapokumaapp-cb587',
    storageBucket: 'kitapokumaapp-cb587.firebasestorage.app',
    iosBundleId: 'com.example.kitapOkumaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OkkRrLzptj2jTZMg0twDihO-lwcKOgQ',
    appId: '1:132808024282:ios:23d079751ac83260bd85e3',
    messagingSenderId: '132808024282',
    projectId: 'kitapokumaapp-cb587',
    storageBucket: 'kitapokumaapp-cb587.firebasestorage.app',
    iosBundleId: 'com.example.kitapOkumaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD4Dkpow9NHSiY5PdZ-MBHKg8tvUPesj8',
    appId: '1:132808024282:web:b51a673f4cff08c7bd85e3',
    messagingSenderId: '132808024282',
    projectId: 'kitapokumaapp-cb587',
    authDomain: 'kitapokumaapp-cb587.firebaseapp.com',
    storageBucket: 'kitapokumaapp-cb587.firebasestorage.app',
  );
}
